# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6


from PyQt5 import QtCore, QtWidgets


class Ui_Admin(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 835)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.room_list_table = QtWidgets.QTableWidget(self.centralwidget)
        self.room_list_table.setGeometry(QtCore.QRect(40, 120, 961, 491))
        self.room_list_table.setObjectName("room_list_table")
        self.room_list_table.setColumnCount(0)
        self.room_list_table.setRowCount(0)
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(40, 40, 91, 41))
        self.back_button.setObjectName("back_button")
        self.room_booking_table = QtWidgets.QTableWidget(self.centralwidget)
        self.room_booking_table.setGeometry(QtCore.QRect(40, 120, 961, 491))
        self.room_booking_table.setObjectName("room_booking_table")
        self.room_booking_table.setColumnCount(0)
        self.room_booking_table.setRowCount(0)
        self.edit_button = QtWidgets.QPushButton(self.centralwidget)
        self.edit_button.setGeometry(QtCore.QRect(1040, 120, 141, 28))
        self.edit_button.setObjectName("edit_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 620, 72, 15))
        self.label.setObjectName("label")
        self.console_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.console_text.setGeometry(QtCore.QRect(40, 650, 961, 131))
        self.console_text.setObjectName("console_text")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(1040, 230, 141, 28))
        self.add_button.setObjectName("add_button")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setGeometry(QtCore.QRect(1040, 290, 141, 28))
        self.delete_button.setObjectName("delete_button")
        self.confirm_button = QtWidgets.QPushButton(self.centralwidget)
        self.confirm_button.setGeometry(QtCore.QRect(1040, 170, 141, 28))
        self.confirm_button.setObjectName("confirm_button")
        self.Building_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.Building_edit.setGeometry(QtCore.QRect(230, 30, 81, 31))
        self.Building_edit.setObjectName("Building_edit")
        self.CapacityMin_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.CapacityMin_edit.setGeometry(QtCore.QRect(370, 30, 81, 31))
        self.CapacityMin_edit.setObjectName("CapacityMin_edit")
        self.CapacityMax_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.CapacityMax_edit.setGeometry(QtCore.QRect(510, 30, 81, 31))
        self.CapacityMax_edit.setObjectName("CapacityMax_edit")
        self.Type_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.Type_edit.setGeometry(QtCore.QRect(630, 30, 81, 31))
        self.Type_edit.setObjectName("Type_edit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 10, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 10, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(500, 10, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(650, 10, 41, 16))
        self.label_6.setObjectName("label_6")
        self.Facilities_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.Facilities_edit.setGeometry(QtCore.QRect(760, 30, 231, 31))
        self.Facilities_edit.setObjectName("Facilities_edit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(780, 10, 201, 16))
        self.label_7.setObjectName("label_7")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(1040, 50, 141, 41))
        self.search_button.setObjectName("search_button")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(230, 90, 81, 16))
        self.label_8.setObjectName("label_8")
        self.StartTime_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.StartTime_edit.setGeometry(QtCore.QRect(370, 80, 221, 31))
        self.StartTime_edit.setObjectName("StartTime_edit")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(640, 90, 81, 16))
        self.label_9.setObjectName("label_9")
        self.EndTime_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.EndTime_edit.setGeometry(QtCore.QRect(760, 80, 231, 31))
        self.EndTime_edit.setObjectName("EndTime_edit")
        self.export_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_button.setGeometry(QtCore.QRect(1040, 350, 141, 28))
        self.export_button.setObjectName("export_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back_button.setText(_translate("MainWindow", "back"))
        self.edit_button.setText(_translate("MainWindow", "Edit"))
        self.label.setText(_translate("MainWindow", "Console"))
        self.add_button.setText(_translate("MainWindow", "Add"))
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.confirm_button.setText(_translate("MainWindow", "Confirm"))
        self.label_3.setText(_translate("MainWindow", "Building"))
        self.label_4.setText(_translate("MainWindow", "Capacity Min"))
        self.label_5.setText(_translate("MainWindow", "Capacity Max"))
        self.label_6.setText(_translate("MainWindow", "Type"))
        self.label_7.setText(_translate("MainWindow", "Facilities(spilt by \',\')"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.label_8.setText(_translate("MainWindow", "Start Time"))
        self.label_9.setText(_translate("MainWindow", "End Time"))
        self.export_button.setText(_translate("MainWindow", "Export"))
